In [1]:
from utils import *

In [2]:
x = [[1,2,3], [2],[4,5,6,7]]
pad_sents(x, 0)

tensor([[1, 2, 3, 0],
        [2, 0, 0, 0],
        [4, 5, 6, 7]])

In [24]:
x = torch.rand((5,2,3))

In [25]:
x

tensor([[[0.0324, 0.3548, 0.8817],
         [0.8524, 0.4267, 0.5391]],

        [[0.2047, 0.1455, 0.5978],
         [0.5078, 0.5835, 0.6966]],

        [[0.7262, 0.2605, 0.3490],
         [0.3811, 0.1824, 0.1718]],

        [[0.7468, 0.1123, 0.1084],
         [0.7598, 0.8912, 0.4832]],

        [[0.3590, 0.8709, 0.6463],
         [0.9781, 0.3234, 0.1098]]])

In [29]:
x.permute(1,0,2)

AttributeError: 'Tensor' object has no attribute 'permute_'

In [28]:
x

tensor([[[0.0324, 0.3548, 0.8817],
         [0.8524, 0.4267, 0.5391]],

        [[0.2047, 0.1455, 0.5978],
         [0.5078, 0.5835, 0.6966]],

        [[0.7262, 0.2605, 0.3490],
         [0.3811, 0.1824, 0.1718]],

        [[0.7468, 0.1123, 0.1084],
         [0.7598, 0.8912, 0.4832]],

        [[0.3590, 0.8709, 0.6463],
         [0.9781, 0.3234, 0.1098]]])

In [39]:
import torch.nn as nn
X = torch.rand((3,3,3))
source_lengths = [3,2,1]
encoder = nn.LSTM(3,2, bidirectional = True)
# X = nn.utils.rnn.pack_padded_sequence(X, lengths=source_lengths)
# enc_hiddens, (hidden, cell) = encoder(X)
# enc_hiddens, _ = nn.utils.rnn.pad_padded_sequence(enc_hiddens)

In [40]:
X_pack = nn.utils.rnn.pack_padded_sequence(X, lengths=source_lengths)

In [41]:
enc_hiddens, (hidden, cell) = encoder(X_pack)

In [42]:
enc_hiddens, _ = nn.utils.rnn.pad_packed_sequence(enc_hiddens)

In [47]:
enc_hiddens

tensor([[[-0.0809, -0.2559,  0.2001,  0.1162],
         [-0.0781, -0.3003,  0.0108,  0.0408],
         [ 0.0435, -0.1864,  0.0023, -0.0671]],

        [[-0.1183, -0.2855,  0.1205,  0.0702],
         [-0.1089, -0.3104,  0.0658,  0.0196],
         [ 0.0000,  0.0000,  0.0000,  0.0000]],

        [[-0.1311, -0.3429,  0.0445,  0.0451],
         [ 0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000]]], grad_fn=<CopySlices>)

In [44]:
hidden

tensor([[[-0.1311, -0.3429],
         [-0.1089, -0.3104],
         [ 0.0435, -0.1864]],

        [[ 0.2001,  0.1162],
         [ 0.0108,  0.0408],
         [ 0.0023, -0.0671]]], grad_fn=<StackBackward>)

In [36]:
hidden

tensor([[[ 0.0176, -0.0277],
         [ 0.0352, -0.1002],
         [-0.0018, -0.0512]],

        [[ 0.1072,  0.0943],
         [ 0.0434,  0.0758],
         [ 0.0302,  0.1004]]], grad_fn=<StackBackward>)

In [45]:
_, (a, _) = encoder(X)

In [46]:
a

tensor([[[-0.1311, -0.3429],
         [-0.0880, -0.3242],
         [-0.0731, -0.3028]],

        [[ 0.2001,  0.1162],
         [ 0.0322,  0.0349],
         [ 0.0823, -0.0195]]], grad_fn=<StackBackward>)

In [2]:
!python sanity_check.py 1d

Running Sanity Check for Question 1d: Encode
--------------------------------------------------------------------------------
enc_hiddens Sanity Checks Passed!
dec_init_state[0] Sanity Checks Passed!
dec_init_state[1] Sanity Checks Passed!
--------------------------------------------------------------------------------
All Sanity Checks Passed for Question 1d: Encode!
--------------------------------------------------------------------------------


In [7]:
!python sanity_check.py 1f

--------------------------------------------------------------------------------
Running Sanity Check for Question 1f: Step
--------------------------------------------------------------------------------
dec_state[0] Sanity Checks Passed!
dec_state[1] Sanity Checks Passed!
combined_output  Sanity Checks Passed!
e_t Sanity Checks Passed!
--------------------------------------------------------------------------------
All Sanity Checks Passed for Question 1f: Step!
--------------------------------------------------------------------------------
